### ISSUE TITLE
Raise error/warning when using :for/:if on a renderless component

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface#189]
We should raise a compile-time error if the user tries to use `:for` or any incompatible directive on a renderless component. 

It should accept the same directives as `<template>`, which currently is just `:let`:https://github.com/msaraiva/surface/blob/b745e1322ce7b20fcbcf8503f507349da0772435/lib/surface/compiler.ex#L40.

Initial discussion started at https://github.com/msaraiva/surface/issues/182.

**Comment by msaraiva** [comment]
@lnr0626 does this still apply? How https://github.com/surface-ui/surface/pull/283 impact this?

**Comment by Zurga** [comment]
Maybe there is a use case for looping over renderless components: to changes to the children. 

In SurfaceBulma, I am trying to implement card the Card with the following capability:
```
<Card>
  <Footer>
     <a>Footer 1</a>
     <a>Footer 2</a>
     <a>Footer 3</a>
   </Footer>
</Card>
```
I want to either, inject the `card-footer-item` class into the `a` tags specified in the `Footer`, or I would like to wrap them in a `<div class="card-footer-item">`. 
I have not found a way yet to do this, if there is one way to do it at the moment, please let me know.

**Comment by msaraiva** [comment]
Since we're deprecating `:for` in favour of `{#for}`, I think we can let this one go.

**Comment by lnr0626** [comment]
@msaraiva do we want to keep it around for `:if`?

**Comment by msaraiva** [comment]
I totally missed `:if`. Yeah, I guess we should keep it.

**Comment by phgrey** [comment]
probably have the same issue when using `:if`, `{#if}`, `:for` & `{#for}`

surface version:
`"surface": {:hex, :surface, "0.10.0", "54eeb1bc7d3e411e3cbd1074237f4369afb24c4e3177ba26f6aaf62336533197", ...`

Have parent component Tabs.List with slot :tabs
Children component Tabs.Tab is defined to hold the :tabs slot's content - `use Surface.Component, slot: "tabs"`

When using Tabs.Tab with :if or :for directive - got error:
```
** (KeyError) key :opts not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (surface 0.10.0) lib/surface/compiler/eex_engine.ex:777: Surface.Compiler.EExEngine.generator_binding/2
    (surface 0.10.0) lib/surface/compiler/eex_engine.ex:711: Surface.Compiler.EExEngine.handle_slot_entries/4
    (surface 0.10.0) lib/surface/compiler/eex_engine.ex:581: anonymous fn/5 in Surface.Compiler.EExEngine.build_slot_props/4
    (elixir 1.14.1) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (elixir 1.14.1) lib/enum.ex:2480: Enum.map/2
    (surface 0.10.0) lib/surface/compiler/eex_engine.ex:578: Surface.Compiler.EExEngine.build_slot_props/4
    (surface 0.10.0) lib/surface/compiler/eex_engine.ex:362: Surface.Compiler.EExEngine.to_expression/3
```

Inserting `dbg({module, props, name})` in deps/surface/lib/surface/compiler/eex_engine.ex:776 gives
```
[lib/surface/compiler/eex_engine.ex:776: Surface.Compiler.EExEngine.generator_binding/2]
{module, props, name} #=> {Moon.Design.Tabs.List, [], :default}
```
Looks like it's trying to use `:default` slot instead of desired `:tabs`
