### ISSUE TITLE
"unknown application" on initial compile

### ISSUE THREAD

**Issue by neilberkman** [surface-ui/surface#349]
With surface 0.3.1, after doing `mix clean` and compiling I get `unknown application: :myapp`, which is comping from a call to `Application.app_dir()`, which is called by `Mix.Tasks.Compile.Surface.get_colocated_assets/`. This is cleared up by a second `mix compile`. 

```
$ mix clean ; mix compile
** (ArgumentError) unknown application: :myapp
    (elixir 1.11.4) lib/application.ex:896: Application.app_dir/1
    (surface 0.3.2) lib/mix/tasks/compile/surface.ex:138: Mix.Tasks.Compile.Surface.app_modules/1
    (surface 0.3.2) lib/mix/tasks/compile/surface.ex:56: anonymous fn/2 in Mix.Tasks.Compile.Surface.get_colocated_assets/0
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.3.2) lib/mix/tasks/compile/surface.ex:14: Mix.Tasks.Compile.Surface.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.ex:119: Mix.Tasks.Compile.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.11.4) lib/code.ex:931: Code.require_file/2
$ mix compile
Compiling 213 files (.ex)
Generated myapp app
```

**Comment by msaraiva** [comment]
Hi @neilberkman!

Just to get a bit more information, how is your project's `compilers` entry configured in `mix.exs`? Is it something like:

```
def project do
  [
    ...,
    compilers: [:phoenix] ++ Mix.compilers() ++ [:surface]
  ]
end
```

**Comment by neilberkman** [comment]
It was not, and that fixed it. Thanks!
