### ISSUE TITLE
Cannot update to 0.5

### ISSUE THREAD

**Issue by lstrzebinczyk** [surface-ui/surface#442]
Hey! Let me start by saying I absolutely love surface, it's enabling me to take a shot at live view, and a general pleasure to work with.

Having that said, I'm having some troubles upgrading to 0.5 version. The timeline is this:
1. I had a non-live-view project
2. I upgraded it to live view and used surface 0.2.1 at the time, since that was the state of the art. 
3. Now I'm trying to upgrade to 0.5

When I run `mix deps.compile`, as suggested by the migration script, I get this error: 

```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for Mix.Tasks.Compile.Surface.generate_files/2

def(generate_files({js_files, _css_files}, build_time)) do
  opts = Application.get_env(:surface, :compiler, [])
  hooks_output_dir = Keyword.get(opts, :hooks_output_dir, "assets/js/_hooks")
  js_output_dir = Path.join([File.cwd!(), hooks_output_dir])
  index_file = Path.join([js_output_dir, "index.js"])
  File.mkdir_p!(js_output_dir)
  unused_hooks_files = delete_unused_hooks_files!(js_output_dir, js_files)
  index_file_time = case(File.stat(index_file)) do
    {:ok, %File.Stat{mtime: time}} ->
      time
    _ ->
      nil
  end
  update_index? = for({src_file, dest_file_name} <- js_files, dest_file = Path.join(js_output_dir, dest_file_name), {:ok, %File.Stat{mtime: time}} <- [File.stat(src_file)], case(case(File.exists?(dest_file)) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      true
    _ ->
      false
  end) do
    false ->
      :erlang.>(time, index_file_time)
    true ->
      true
  end, do: (_ -> (
    content = [header(build_time), "\n\n", File.read!(src_file)]
    File.write!(dest_file, content)
    true
  )), reduce: false)
  case(case(case(case(index_file_time) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      true
    _ ->
      false
  end) do
    false ->
      update_index?
    true ->
      true
  end) do
    false ->
      :erlang."/="(unused_hooks_files, [])
    true ->
      true
    other ->
      :erlang.error({:badbool, :or, other})
  end) do
    x when :erlang.orelse(:erlang."=:="(x, false), :erlang."=:="(x, nil)) ->
      nil
    _ ->
      File.write!(index_file, index_content(js_files, build_time))
  end
end

Please report this bug: https://github.com/elixir-lang/elixir/issues

** (KeyError) key :version not found in: [line: 46]
        (elixir 1.11.0) lib/keyword.ex:420: Keyword.fetch!/2
        (elixir 1.11.0) lib/module/types/unify.ex:318: Module.Types.Unify.get_var!/2
        (elixir 1.11.0) lib/module/types/expr.ex:112: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:374: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:83: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:289: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/expr.ex:136: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types/helpers.ex:106: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.0) lib/module/types/expr.ex:195: Module.Types.Expr.of_expr/3
        (elixir 1.11.0) lib/module/types.ex:63: Module.Types.warnings_from_clause/6
        (elixir 1.11.0) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.11.0) lib/enum.ex:3421: Enum.flat_map_list/2
        (elixir 1.11.0) lib/enum.ex:3422: Enum.flat_map_list/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.11.0) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
```

And I have no idea what to make of this. Thoughts?

**Comment by msaraiva** [comment]
Hi @lstrzebinczyk!

I can't reproduce the issue but it seems you may have some outdated beams. Have you try to remove `_build` and recompile the project? I have also seen people reporting similar issues when using ElixirLS on VS Code. If that's the case, you can try to remove the `.elixir_ls` folder too.

Additionally, there was this issue https://github.com/elixir-lang/elixir/issues/10224 that might be related, so you could try to update Elixir if nothing else works.

**Note**: It's be safer to migrate to `v0.4.1` and fix any warning you might have before running the converter. Was that the path you took?

**Comment by lstrzebinczyk** [comment]
@msaraiva Updating to elixir 1.12.1 did the trick!
Thank you very much, and have a nice day : )
