### ISSUE TITLE
Bug: ErrorTag crashes on Ecto.Enum cast error.

### ISSUE THREAD

**Issue by ppiechota** [surface-ui/surface#450]
## Describe the bug

ErrorTag crashes LV when there is cast error on a schema field being Ecto.Enum type.

```
[error] GenServer #PID<0.562.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:parameterized, Ecto.Enum, %{on_dump: %{B2B: "B2B", EoC: "EoC"}, on_load: %{"B2B" => :B2B, "EoC" => :EoC}, type: :string, values: [:B2B, :EoC]}} of type Tuple
    (elixir 1.12.1) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.12.1) lib/string/chars.ex:22: String.Chars.to_string/1
    (surface 0.5.0) lib/surface/components/form/error_tag.ex:127: anonymous fn/2 in Surface.Components.Form.ErrorTag.translate_error/1
    (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.5.0) lib/surface/components/form/error_tag.ex:112: anonymous fn/7 in Surface.Components.Form.ErrorTag.render/1
```

Probably `translate_error` function doesn't handle Ecto.Enum type properly:
```
def translate_error({msg, opts}) do
    # Because the error messages we show in our forms and APIs
    # are defined inside Ecto, we need to translate them dynamically.
    Enum.reduce(opts, msg, fn {key, value}, acc ->
      String.replace(acc, "%{#{key}}", to_string(value))
    end)
  end
```

`to_string` function receives and cannot handle below tuple which is a part of meta keyword list under errors in a changeset:
```
{:parameterized, Ecto.Enum,
        %{
          on_dump: %{B2B: "B2B", EoC: "EoC"},
          on_load: %{"B2B" => :B2B, "EoC" => :EoC},
          type: :string,
          values: [:B2B, :EoC]
        }
```

Errors key under Changeset:
```
 errors: [
    company_id: {"can't be blank", [validation: :required]},
    type: {"is invalid",
     [
       type: {:parameterized, Ecto.Enum,
        %{
          on_dump: %{B2B: "B2B", EoC: "EoC"},
          on_load: %{"B2B" => :B2B, "EoC" => :EoC},
          type: :string,
          values: [:B2B, :EoC]
        }},
       validation: :cast
     ]},
    country_id: {"is invalid", [type: :id, validation: :cast]}
  ],
  data: #Flip.Schemas.DB.Employee<>,
  valid?: false
```

## How to reproduce it

Employee.ex
```
defmodule Example.Schemas.DB.Employee do
  use Ecto.Schema
  alias Ecto.Changeset

  schema "employee" do
    field :type, Ecto.Enum, values: [:B2B, :EoC]

  def changeset(%__MODULE__{} = employee, params) do
    employee
    |> Changeset.cast(params, all_fields())
 end

  defp all_fields do
    __MODULE__.__schema__(:fields)
  end
```

Form.ex (only render function)

```
  @impl true
  def render(assigns) do
    ~F"""

    <div class="container is-fullhd">

        <h2 class="title">
          New consultant form:
        </h2>

      <div class="tile">
        <div class="column is-half">

      <!-- Form begins here -->
        <Form for={ @changeset } submit="create_consultant" change="validate_consultant">

          <Field name={ :type } class="field">
            <Label class="label" />
            <TextInput class="input is-normal" />
            <ErrorTag />
          </Field>

          <!-- Form submit button -->
          <Submit class="button is-success">
            Submit
          </Submit>
        </Form>

        <!-- Form ends here -->
      </div>
    </div>
    </div>
    """
  end
```

## The behavior you expected
'Is invalid' error message displayed under a field of Ecto.Enum type when TextInput provided with a not allowed value - smoething else than :B2B or :CoE  `field :type, Ecto.Enum, values: [:B2B, :EoC]`

## Your Environment
Surface: v0.5.0
LiveView: v0.15.1
Elixir: v1.12.1

**Comment by ppiechota** [comment]
Temporary solution:

```
<Field name={ :type } class="field">
  <Label class="label" />
  <TextInput class="input is-normal" />
  <ErrorTag translator={fn _ -> "test error message" end}/>
</Field>
```

But it would be better to have it handled by default.

**Comment by davydog187** [comment]
Hello @ppiechota, thanks for reporting!

Have you tried implementing your own `translate_error/1` function? In the [ErrorTag](https://surface-ui.org/builtincomponents/ErrorTag) docs, it shows how you can configure this.


```elixir
config :surface, :components, [
  {Surface.Components.Form.ErrorTag, default_translator: {MyAppWeb.ErrorHelpers, :translate_error}}
]
```

Surface only provides a fallback implementation, so if you want it to work robustly for all the types your application expects, this is probably the way to go.

**Comment by ppiechota** [comment]
Thanks @davydog187. So basically I can reffer to Phoenix default translator defined in error_helpers.ex.

I tried it and now it works. I just don't get it why Surface doesntt use it directly by default? Because of potential Gettext overhead?

**Comment by davydog187** [comment]
@ppiechota mostly because rendering will be specific to your application, and Surface is not trying to prescribe any particular markup. In the case of `Gettext`, that is a dependency that shouldn't be introduced to Surface. Instead, Surface provides this escape hatch so you can render errors however you want :)

**Comment by msaraiva** [comment]
Closing this in favor of https://github.com/surface-ui/surface/pull/449.
