### ISSUE TITLE
Build error in dockerfile `RUN mix assets.deploy`

### ISSUE THREAD

**Issue by Knovour** [surface-ui/surface#619]
## Describe the bug
Docker build error after install surface package

## How to reproduce it
1. install surface
2. `mix surface.init`
3. create dockerfile then `docker build .`
```dockerfile
FROM elixir:1.13.4-alpine AS build

# install build dependencies
RUN apk add --no-cache --update build-base git python3 curl

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV=prod

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV

RUN mkdir config
COPY config/config.exs config/$MIX_ENV.exs config/
RUN mix deps.compile

COPY priv priv
COPY assets assets
# ERROR HERE
RUN mix assets.deploy

# compile and build release
COPY lib lib
RUN mix compile

COPY config/runtime.exs config/
RUN mix release

# prepare release image
FROM alpine AS app
RUN apk add --no-cache openssl libgcc libstdc++ ncurses-libs

WORKDIR /app

RUN chown nobody:nobody /app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/surface_docker ./
ENV HOME=/app

CMD ["bin/surface_docker", "start"]
```

error messages
```bash
 => ERROR [build 12/16] RUN mix assets.deploy                                                                                          2.0s
------
 > [build 12/16] RUN mix assets.deploy:
#21 0.417
#21 0.417 04:19:04.975 [debug] Downloading esbuild from https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.14.29.tgz
#21 1.931
#21 1.931   ../priv/static/assets/app.js   88.6kb
#21 1.931   ../priv/static/assets/app.css  11.3kb
#21 1.931
#21 1.931 ⚡ Done in 10ms
#21 1.987 Generated surface_docker app
#21 1.999 ** (MatchError) no match of right hand side value: {:error, {'no such file or directory', 'surface_docker.app'}}
#21 1.999     (surface 0.7.4) lib/mix/tasks/compile/surface.asset_generator.ex:158: Mix.Tasks.Compile.Surface.AssetGenerator.components/0
#21 1.999     (surface 0.7.4) lib/mix/tasks/compile/surface.asset_generator.ex:52: Mix.Tasks.Compile.Surface.AssetGenerator.get_colocated_assets/0
#21 1.999     (surface 0.7.4) lib/mix/tasks/compile/surface.asset_generator.ex:12: Mix.Tasks.Compile.Surface.AssetGenerator.run/0
#21 1.999     (surface 0.7.4) lib/mix/tasks/compile/surface.ex:52: Mix.Tasks.Compile.Surface.run/1
#21 1.999     (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
#21 1.999     (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
#21 1.999     (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
#21 1.999     (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
------
executor failed running [/bin/sh -c mix assets.deploy]: exit code: 1
```

Demo: https://github.com/Knovour/surface_docker

## The behavior you expected
build complete

## Your Environment
Surface: v0.7.4
LiveView: v0.17.5
Elixir: v1.13.4

**Comment by Knovour** [comment]
It seems ok now, thank you!

**Comment by karlosmid** [comment]
Hi! For me it fails on `mix  compile`
