### ISSUE TITLE
Error on printing diagnostics when hot code reloading

### ISSUE THREAD

**Issue by mayel** [surface-ui/surface#754]
## Describe the bug

```
warning: variable "opts" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/static_generator/maybe_static_generator_plug.ex:13:32
** (Protocol.UndefinedError) protocol String.Chars not implemented for {39, 9} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Cldr.Calendar.Duration, Cldr.Currency, Cldr.LanguageTag, Cldr.LanguageTag.T, Cldr.LanguageTag.U, Cldr.Unit, Complex, Date, DateTime, Decimal, [...]
    (elixir 1.17.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.17.3) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir 1.17.3) lib/exception.ex:769: Exception.format_file_line/3
    (elixir 1.17.3) lib/exception.ex:638: Exception.format_stacktrace_entry/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors."-print_diagnostic/2-lc$^0/1-0-"/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors.print_diagnostic/2
    (elixir 1.17.3) src/elixir_errors.erl:106: :elixir_errors.emit_diagnostic/6
    (surface 0.12.0) lib/mix/tasks/compile/surface.ex:200: anonymous fn/2 in Mix.Tasks.Compile.Surface.print_diagnostics/1
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.12.0) lib/mix/tasks/compile/surface.ex:199: Mix.Tasks.Compile.Surface.print_diagnostics/1
    (surface 0.12.0) lib/mix/tasks/compile/surface.ex:191: Mix.Tasks.Compile.Surface.handle_diagnostics/2
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:307: Phoenix.CodeReloader.Server.run_compilers/3
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:335: Phoenix.CodeReloader.Server.with_logger_app/2
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:262: Phoenix.CodeReloader.Server.mix_compile/4
    (mix 1.17.3) lib/mix/project.ex:463: Mix.Project.in_project/4
    (elixir 1.17.3) lib/file.ex:1665: File.cd!/2
    (mix 1.17.3) lib/mix/dep.ex:266: Mix.Dep.in_dependency/3
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:206: anonymous fn/7 in Phoenix.CodeReloader.Server.mix_compile_deps/6
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:205: Phoenix.CodeReloader.Server.mix_compile_deps/6
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:187: Phoenix.CodeReloader.Server.mix_compile/5
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:74: anonymous fn/4 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:299: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix 1.7.14) lib/phoenix/code_reloader/server.ex:72: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib 6.1) gen_server.erl:2381: :gen_server.try_handle_call/4
    (stdlib 6.1) gen_server.erl:2410: :gen_server.handle_msg/6
    (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3

```
## How to reproduce it
1. Start phoenix/surface app with hot code reload enabled
2. Load a page or edit a surface module
3. Error appears

## Your Environment
Surface: v0.12.0
LiveView: v0.20.17
Elixir: v11.17.3

**Comment by simonmcconnell** [comment]
I get a similar error when  putting `:for={...}` on a Surface component.

```
Compiling 1 file (.ex)
** (Protocol.UndefinedError) protocol String.Chars not implemented for {84, 14} of type Tuple
    (elixir 1.17.3) lib/string/chars.ex:3: String.Chars.impl_for!/1    
    (elixir 1.17.3) lib/string/chars.ex:22: String.Chars.to_string/1   
    (elixir 1.17.3) lib/exception.ex:769: Exception.format_file_line/3 
    (elixir 1.17.3) lib/exception.ex:638: Exception.format_stacktrace_entry/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors."-print_diagnostic/2-lc$^0/1-0-"/1
    (elixir 1.17.3) src/elixir_errors.erl:79: :elixir_errors.print_diagnostic/2
    (elixir 1.17.3) src/elixir_errors.erl:106: :elixir_errors.emit_diagnostic/6
    (surface 0.12.0) lib/mix/tasks/compile/surface.ex:200: anonymous fn/2 in Mix.Tasks.Compile.Surface.print_diagnostics/1
```

**Comment by msaraiva** [comment]
Hey @simonmcconnell!

This has been fixed in https://github.com/surface-ui/surface/commit/5a11bc4925bc676b6e739905144729d47af4a29f. There are a couple of other issues I'm currently working on. All related to diagnostics. I'll push a patch release as soon as I fix them.
